"""
Adaptive VAD Tuner — Stage 3
=============================
Session-level adaptive tuning algorithm derived from the Stage 2 Pareto model.

STATUS: Stage 1 complete. pareto_model.json is generated by analyse_sweep.py
and committed to the repository. Load via from_pareto_file().

If pareto_model.json is missing, a FileNotFoundError is raised
intentionally so the absence does not go unnoticed.

Usage:

    from adaptive_tuner import AdaptiveVADTuner

    # Load Pareto model produced by analyse_sweep.py (committed to repo)
    tuner = AdaptiveVADTuner.from_pareto_file("model.json", omega=0.7)

    # In your WebSocket receive loop:
    await tuner.update_if_needed(ws, metrics_collector)

Interface contract:
    - omega (float, 0–1): relative weight of FPR vs TL reduction.
      0.0 = minimise TL only, 1.0 = minimise FPR only.
    - update_interval_s: minimum seconds between session.update emissions.
    - delta: minimum parameter change norm required to emit an update.

Reference:
    Algorithm 1 in the accompanying paper (paper/VAD_Optimisation_IEEE_TLT_preprint.pdf).
"""

import json
import logging
import time
from pathlib import Path
from typing import Optional

logger = logging.getLogger("vad.adaptive_tuner")


# ── Pareto Model ──────────────────────────────────────────────────────────────


class ParetoModel:
    """
    Holds the Pareto-optimal VAD configurations identified in Stage 2.

    Populated by analyse_sweep.py once sweep data is available.
    Each point is a dict with keys: threshold, silence_duration_ms,
    prefix_padding_ms, fpr, tl_ms.
    """

    def __init__(self, points: list[dict]):
        if not points:
            raise ValueError("Pareto model requires at least one point.")
        self.points = points

    @classmethod
    def from_file(cls, path: str | Path) -> "ParetoModel":
        """Load from JSON file written by analyse_sweep.py."""
        data = json.loads(Path(path).read_text())
        return cls(data["pareto_points"])

    def nearest(self, omega: float) -> dict:
        """
        Return the Pareto point that minimises the scalarised objective:

            s = omega * FPR_normalised + (1 - omega) * TL_normalised

        Falls back to the first point if FPR/TL values are not yet available.
        """
        points_with_scores = [
            p
            for p in self.points
            if p.get("fpr") is not None and p.get("tl_ms") is not None
        ]

        if not points_with_scores:
            # Stage 2 not yet complete — return centre point
            return self.points[0]

        fpr_vals = [p["fpr"] for p in points_with_scores]
        tl_vals = [p["tl_ms"] for p in points_with_scores]

        fpr_min, fpr_max = min(fpr_vals), max(fpr_vals)
        tl_min, tl_max = min(tl_vals), max(tl_vals)

        def score(p: dict) -> float:
            fpr_n = (p["fpr"] - fpr_min) / max(fpr_max - fpr_min, 1e-9)
            tl_n = (p["tl_ms"] - tl_min) / max(tl_max - tl_min, 1e-9)
            return omega * fpr_n + (1 - omega) * tl_n

        return min(points_with_scores, key=score)


# ── Adaptive Tuner ────────────────────────────────────────────────────────────


class AdaptiveVADTuner:
    """
    Session-level adaptive VAD tuner.

    Observes live FPR and TL from the metrics collector and emits
    session.update events when the current configuration is sub-optimal
    relative to the Stage 2 Pareto model.

    The algorithm corresponds to Algorithm 1 in the paper:
      1. Initialise θ at the centre of the Pareto model.
      2. Every Δt seconds, observe FPR_n and TL_n from the event stream.
      3. Compute scalarised objective s_n = ω·FPR_n + (1−ω)·TL̃_n.
      4. Find θ* = argmin s(θ) over the Pareto front.
      5. If ‖θ − θ*‖ > δ, emit session.update and set θ ← θ*.
      6. Repeat until convergence or session end.
    """

    # Minimum parameter change norm required to emit an update.
    # Prevents thrashing on small differences.
    DEFAULT_DELTA = 0.05

    def __init__(
        self,
        pareto_model: Optional[ParetoModel] = None,
        omega: float = 0.7,
        update_interval_s: float = 30.0,
        delta: float = DEFAULT_DELTA,
    ):
        """
        Args:
            pareto_model:      Fitted Pareto model from Stage 2.
                               Pass None to disable adaptive tuning
                               (update_if_needed becomes a no-op).
            omega:             FPR weight in scalarised objective [0, 1].
                               0.7 prioritises FPR reduction over latency.
            update_interval_s: Minimum seconds between session.update calls.
            delta:             Minimum normalised parameter distance to trigger update.
        """
        self.pareto_model = pareto_model
        self.omega = omega
        self.update_interval_s = update_interval_s
        self.delta = delta

        self._current_config: Optional[dict] = None
        self._last_update_time: Optional[float] = None
        self._n_updates: int = 0

        if pareto_model is not None:
            self._current_config = self._vad_config(pareto_model.nearest(omega))
            logger.info(
                f"AdaptiveVADTuner initialised: omega={omega}, "
                f"initial config={self._current_config}"
            )
        else:
            logger.info(
                "AdaptiveVADTuner initialised without Pareto model — "
                "adaptive tuning disabled until load_pareto_model() is called."
            )

    # ── Factory methods ───────────────────────────────────────────────────────

    @classmethod
    def from_pareto_file(cls, path: str | Path, **kwargs) -> "AdaptiveVADTuner":
        """Load Pareto model from a JSON file written by analyse_sweep.py."""
        return cls(pareto_model=ParetoModel.from_file(path), **kwargs)

    # ── Public API ────────────────────────────────────────────────────────────

    @property
    def is_ready(self) -> bool:
        """True if a Pareto model is loaded and contains scored points."""
        if self.pareto_model is None:
            return False
        return any(p.get("fpr") is not None for p in self.pareto_model.points)

    def load_pareto_model(self, path: str | Path):
        """
        Load (or replace) the Pareto model at runtime.
        Allows Stage 2 results to be applied to a running system
        without restarting.
        """
        self.pareto_model = ParetoModel.from_file(path)
        self._current_config = self._vad_config(self.pareto_model.nearest(self.omega))
        logger.info(
            f"Pareto model loaded from {path}. Initial config: {self._current_config}"
        )

    async def update_if_needed(self, ws, metrics_collector) -> bool:
        """
        Observe current metrics, compare against Pareto front, and emit
        session.update if a better configuration exists.

        Call this method from your WebSocket receive loop or on a timer.

        Args:
            ws:                aiohttp WebSocketResponse (open connection).
            metrics_collector: MetricsCollector instance with live metrics.

        Returns:
            True if a session.update was emitted, False otherwise.
        """
        if self.pareto_model is None:
            return False

        now = time.time()
        if (
            self._last_update_time is not None
            and now - self._last_update_time < self.update_interval_s
        ):
            return False

        # Observe current FPR and TL from live event stream
        snapshot = metrics_collector.get_run_snapshot()
        current_fpr = snapshot["openai"].get("fpr", 0.0)
        current_tl = snapshot["openai"].get("response_latency_ms", 0.0)

        # Find optimal Pareto point for current omega
        target = self.pareto_model.nearest(self.omega)
        target_config = self._vad_config(target)

        # Compute normalised parameter distance
        if self._current_config is not None:
            dist = self._param_distance(self._current_config, target_config)
        else:
            dist = float("inf")

        if dist <= self.delta:
            logger.debug(f"AdaptiveVADTuner: no update needed (dist={dist:.4f})")
            return False

        # Emit session.update
        await self._emit_update(ws, target_config)
        self._current_config = target_config
        self._last_update_time = now
        self._n_updates += 1

        logger.info(
            f"AdaptiveVADTuner update #{self._n_updates}: "
            f"FPR={current_fpr:.3f} TL={current_tl:.0f}ms → {target_config}"
        )
        return True

    # ── Internal ──────────────────────────────────────────────────────────────

    @staticmethod
    def _vad_config(point: dict) -> dict:
        return {
            "threshold": point["threshold"],
            "silence_duration_ms": point["silence_duration_ms"],
            "prefix_padding_ms": point["prefix_padding_ms"],
        }

    @staticmethod
    def _param_distance(a: dict, b: dict) -> float:
        """
        Normalised Euclidean distance between two VAD configurations.
        Each parameter is normalised by its expected range.
        """
        ranges = {
            "threshold": 0.45,  # 0.40 – 0.85
            "silence_duration_ms": 850,  # 350 – 1200
            "prefix_padding_ms": 300,  # 200 – 500
        }
        return sum(((a[k] - b[k]) / ranges[k]) ** 2 for k in ranges) ** 0.5

    @staticmethod
    async def _emit_update(ws, vad_config: dict):
        """Send session.update to OpenAI Realtime API."""
        await ws.send_json(
            {
                "type": "session.update",
                "session": {
                    "turn_detection": {
                        "type": "server_vad",
                        "threshold": vad_config["threshold"],
                        "silence_duration_ms": vad_config["silence_duration_ms"],
                        "prefix_padding_ms": vad_config["prefix_padding_ms"],
                        "interrupt_response": True,
                    }
                },
            }
        )
